name: mwwm_template
description: Mwwm template with get_it
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  pedantic: ^1.9.0
  rxdart: ^0.24.1
  intl: ^0.16.1
  shared_preferences: ^0.5.10

  # dependency injection
  get_it: ^4.0.4
  injectable: ^1.0.4

  # surf lib
  surf_network: ^0.0.1-dev.4
  surf_mwwm: ^0.0.1-dev.2
  bottom_sheet: ^0.0.1-dev.2
  surf_logger: ^0.0.1-dev.4

  # mwwm packages
  mwwm: ^0.1.1
  relation: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  injectable_generator: ^1.0.4

  build_runner: ^1.10.2

flutter:
  uses-material-design: true
